/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VUES;
import DAO.critiqueDAO;
import METIERS.Critique;
import METIERS.Role;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import VUES.recherche_frame;

/**
 *
 * @author Game_K
 */
public class main_frame extends javax.swing.JFrame {

    private Role role;
    private DefaultTableModel modeleTable;
    private ArrayList<Critique> listMessages = null;
    /**
     * Creates new form main_frame
     */
    public main_frame(Role role) throws SQLException {
        initComponents();
        this.role = role;
        this.setTitle("Resto FR - Administration [" + role.getLibelle() + "]");
        modeleTable = new DefaultTableModel();
        jTable1.setModel(modeleTable);
        jButtonDelMsg.setEnabled(role.getId() == 3);
    }
    
    public void setMessageList(ArrayList<Critique> listMessages) {
        this.listMessages = listMessages;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonHideMsg = new javax.swing.JButton();
        jButtonDelMsg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Utilisateur", "Restaurant", "Date", "Message", "Masquer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonHideMsg.setText("Masquer");
        jButtonHideMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHideMsgActionPerformed(evt);
            }
        });

        jButtonDelMsg.setText("Supprimer");

        jButton1.setText("Recherche");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHideMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHideMsg)
                    .addComponent(jButtonDelMsg)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHideMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHideMsgActionPerformed

        Critique select = this.listMessages.get(jTable1.getSelectedRow());
        System.out.println(select);

        int inverseStatus = 1;
        String afficheStatus = "Masquer";
        if (jTable1.getValueAt(jTable1.getSelectedRow(), 4) == afficheStatus) {
            inverseStatus = 0;
            afficheStatus = "Afficher";
        }

        try {
            critiqueDAO.setMasquerById(select.getUnResto().getId(), select.getUnUtilisateur().getId(), inverseStatus);
            modeleTable.setValueAt(afficheStatus, jTable1.getSelectedRow(), 4);

            afficheStatus = "Afficher";
            if (inverseStatus == 0) {
                afficheStatus = "Masquer";
            }
            jButtonHideMsg.setText(afficheStatus);            
            
        } catch (SQLException ex) {
            Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonHideMsgActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int rep = JOptionPane.showConfirmDialog(null, "Quitter l'application\nEtes-vous sûr(e) ?", "Resto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (rep == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getValueAt(jTable1.getSelectedRow(), 4) == "Masquer") {
            jButtonHideMsg.setText("Afficher");
        }
        if (jTable1.getValueAt(jTable1.getSelectedRow(), 4) == "Afficher") {
            jButtonHideMsg.setText("Masquer");
        } 
    }//GEN-LAST:event_jTable1MouseClicked

    public DefaultTableModel getModeleTable() {
        return modeleTable;
    }

    public void setModeleTable(DefaultTableModel modeleTable) {
        this.modeleTable = modeleTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelMsg;
    private javax.swing.JButton jButtonHideMsg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
